### PR TITLE
Add style and slot transforms

### PR DESCRIPTION
**Pull request by macdonst**

### CODE REVIEW

**Review by ryanbethel — APPROVED** [review]
LGTM. I have used it for a while and I think this is working as intended.

**Comment by macdonst** [comment]
@ryanbethel Just need to figure out why Playwright isn't working properly later today.

**Comment by ryanbethel** [comment]
> @ryanbethel Just need to figure out why Playwright isn't working properly later today.

You mean on Github Actions right? It is working for me locally. I think playwright needs updated. I have not done that in the github action so I am not sure of the process.

**Comment by ryanbethel** [comment]
Its the thing where locally you need to run npx playwright so it updates all the browser binaries. I am not sure how to do that for Github actions. I will investigate a bit.

**Review by kristoferjoseph — APPROVED** [review]

**Comment by kristoferjoseph** [comment]
fwiw this was needed to get playwright to update successfully when they pushed their breaking major release:
https://github.com/enhance-dev/enhance-element/blob/main/package.json#L13-L14

**Pull request merged**
